### ISSUE TITLE
Remove open sores.

### ISSUE THREAD

**Issue by GoatSee** [Sneeds-Feed-and-Seed/sneedacity.org#5]
I think there might be a typo in the pages/about.html file
>Is all software you produce open source?
>Yes, all software we develop and distribute is open source; feel free to contribute if you would be so generous as to do so.

>open source

There is a fundamental difference between free and "open source" software. While the first means that the software respects 4 essential user freedoms[1] and discourages using nonfree software alongside of it, the latter only signifies that you can look at the source code. Ex. Open Watcom” is nonfree because its license does not allow making a modified version and using it privately. Fortunately, few programs use such licenses.

from https://www.gnu.org/philosophy/open-source-misses-the-point.en.html, by Richard Stallman
"The main initial motivation of those who split off the open source camp from the free software movement was that the ethical ideas of “free software” made some people uneasy. That's true: raising ethical issues such as freedom, talking about responsibilities as well as convenience, is asking people to think about things they might prefer to ignore, such as whether their conduct is ethical. This can trigger discomfort, and some people may simply close their minds to it. It does not follow that we ought to stop talking about these issues."
![Well, anon?](https://files.catbox.moe/vvd7fl.jpg)
[1] https://www.gnu.org/philosophy/free-sw.html#f1

**Comment by parkbanks** [comment]
I shall update the about section presently the clarify the distinction and note that Sneedacity is free *and* open source.
